---
- name: Use controller playbook on worker nodes
  hosts: workers
  remote_user: ubuntu
  become: yes
  become_user: root
  
  roles:
    - role: worker
      systems_manager: spahmatthew@gmail.com