---
# defaults file for controller
etcd_bin: /opt/etcd/bin
etcd_ssl: /etc/etcd/ssl

certs:
  etcd_cert: "{{ inventory_dir }}/certs/kube-keys/kubernetes.pem"
  etcd_key: "{{ inventory_dir }}/certs/kube-keys/kubernetes-key.pem"
  ca_cert: "{{ inventory_dir }}/certs/ca-keys/ca.pem"
  ca_key: "{{ inventory_dir }}/certs/ca-keys/ca-key.pem"
  service_account_cert: "{{ inventory_dir }}/certs/service-account-keys/service-account.pem"
  service_account_key: "{{ inventory_dir }}/certs/service-account-keys/service-account-key.pem"
  kube_controller_manager_cert: "{{ inventory_dir }}/certs/kube-keys/kube-controller-manager.pem"
  kube_controller_manager_key: "{{ inventory_dir }}/certs/kube-keys/kube-controller-manager-key.pem"
  kube_proxy_cert: "{{ inventory_dir }}/certs/kube-keys/kube-proxy.pem"
  kube_proxy_key: "{{ inventory_dir }}/certs/kube-keys/kube-proxy-key.pem"
  kube_scheduler_cert: "{{ inventory_dir }}/certs/kube-keys/kube-scheduler.pem"
  kube_scheduler_key: "{{ inventory_dir }}/certs/kube-keys/kube-scheduler-key.pem"
configs:
  admin: "{{ inventory_dir }}/configs/admin"
kubernetes_library: /var/lib/kubernetes
kubernetes_configs: /etc/kubernetes/config

source_configs_dir: "{{ inventory_dir }}/configs"