---
- name: "Create directory for etcd binaries"
  file:
    path: /opt/etcd/bin
    state: directory
    owner: root
    group: root
    mode: 0700
- name: "Download the tarball into the /tmp directory"
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.4.15/etcd-v3.4.15-linux-amd64.tar.gz
    dest: /tmp/etcd.tar.gz
    owner: root
    group: root
    mode: 0600
    force: True
- name: "Extract the contents of the tarball"
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: /opt/etcd/bin/
    owner: root
    group: root
    mode: 0600
    extra_opts:
      - --strip-components=1
    decrypt: True
    remote_src: True
- name: "Set permissions for etcd"
  file:
    path: /opt/etcd/bin/etcd
    state: file
    owner: root
    group: root
    mode: 0700
- name: "Set permissions for etcdctl"
  file:
    path: /opt/etcd/bin/etcdctl
    state: file
    owner: root
    group: root
    mode: 0700
- name: "Add /opt/etcd/bin/ to the $PATH environment variable"
  lineinfile:
    path: /etc/profile
    line: export PATH="$PATH:/opt/etcd/bin"
    state: present
    create: True
    insertafter: EOF
- name: "Set the ETCDCTL_API environment variable to 3"
  lineinfile:
    path: /etc/profile
    line: export ETCDCTL_API=3
    state: present
    create: True
    insertafter: EOF
- name: "Create a etcd service file"
  copy:
    src: etcd/etcd.service
    remote_src: False
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
- name: "Create a etcd data directory"
  file:
    path: /var/lib/etcd/{{ hostvars[inventory_hostname]['ansible_facts']['hostname'] }}.etcd
    state: directory
    owner: root
    group: root
    mode: 0755
- name: "Stop the etcd service"
  command: systemctl stop etcd
- name: "Create directory for etcd configuration"
  file:
    path: /var/lib/etcd/{{ hostvars[inventory_hostname]['ansible_facts']['hostname'] }}.etcd
    state: "{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - absent
    - directory
- name: "Create directory for etcd configuration"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/etcd
    - /etc/etcd/ssl

